# Generated by Django 2.1.5 on 2019-02-08 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devbase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='organization',
            field=models.ForeignKey(blank=True, default='УА и МО', on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='devbase.Organization'),
        ),
    ]
